spring:
  application:
    name: SpringBoot-SSO-App

  devtools:
      restart:
        enabled: true
      livereload:
        enabled: true


  security:
          oauth2:
            client:
              registration:
                google:
                  client-id: your-google-client-id
                  client-secret: your-google-client-secret
               # scope: openid, profile, email

                facebook:
                  client-id: your-facebook-client-id
                  client-secret: your-facebook-client-secret
                 # scope: openid, profile, email


#                microsoft:
#                  client-id: your-microsoft-client-id
#                  client-secret: your-microsoft-client-secret
#                 # scope: openid, profile, email

#                amazon:
#                  client-id: your-amazon-client-id
#                  client-secret: your-amazon-client-secret
#                  #scope: profile

#              provider:
#                microsoft:
#                  authorization-uri: https://login.microsoftonline.com/common/oauth2/v2.0/authorize
#                  token-uri: https://login.microsoftonline.com/common/oauth2/v2.0/token
#                  user-info-uri: https://graph.microsoft.com/oidc/userinfo
#                  jwk-set-uri: https://login.microsoftonline.com/common/discovery/v2.0/keys
#                  user-name-attribute: name
#
#                amazon:
#                  authorization-uri: https://www.amazon.com/ap/oa
#                  token-uri: https://api.amazon.com/auth/o2/token
#                  user-info-uri: https://api.amazon.com/user/profile
#                  user-name-attribute: name